name: workflow_cicd_api
run-name: ${{ github.actor }} GitHub Actions Workflow CICD API ðŸš€
on:
  push:
    branches:
      - main
    # pour eviter de reconstruire si on modifie un fichier autre que dans src et workflow
    paths:
      - 'src/**'
      - '.github/workflows/cicd_api.yml'

jobs:
  build:
    name: Build-and-Analyse
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # recopie du depot dans executeur
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clone lâ€™historique complet (tous les commits, branches, tags).

      # test d'attente de mise en service du conteneur Mysql
      - name: wait for MySQl to be ready
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done

      - name: Create Database from script
        run: mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} < infra/mysql/dump/script.sql

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu' # Alternative distribution options are available.

      - name: Cache SonarQube packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # build avec fichier properties spÃ©cifique mais plus besoin suite utilisation env dans Dockerfile
        #run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=neojero_apiSpringboot2025 -Dspring.profiles.active=cicd
        # execution en mode non interactif (B) et ExÃ©cute toutes les phases jusqu'Ã  verify, y compris test, et effectue des vÃ©rifications supplÃ©mentaires pour s'assurer que le package est valide.
        # a utiliser lors de script d'automatisation type CICD
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=neojero_apiSpringboot2026

      - name: Charging artefact   # permet de charger un artefact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: target/*.jar
          retention-days: 1

      # message de fin indiquant que tout s'est bien passÃ©
      - run: echo "ðŸ This job's status is ${{ job.status }}."

  Team_Notification:
    name: MS Teams Artefact Available
    runs-on: ubuntu-latest
    needs: build
    steps:
        # this is the new step
        - uses: dchourasia/ms-teams-notification@1.0
          if: always()
          with:
            github-token: ${{ github.token }}
            webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

  docker-build-image-api:
    # verifie que le declenchement provient de la branche main
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      # recuperation du dÃ©pÃ´t
      - uses: actions/checkout@v4

      # installation des outils pour docker
      # Optionnelle
      # QUEMU : pour construite des images multi-plateforme (linux/amd64,linux/arm64,linux/arm/v7)
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      # Docker Buildx est une extension de Docker qui permet de tirer parti de
      # fonctionnalitÃ©s avancÃ©es pour la construction d'images Docker
      # Optionnelle
      - name: Set Up Docker Build
        uses: docker/setup-buildx-action@v3

      # connexion au docker hub
      - name: Connect to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # recupÃ©ration de l'artefact
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: package

      # juste pour le controle
      - name: List files in the repository
        run: ls ${{ github.workspace }}

      # construction de l'image docker et push sur dockerHub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/apispringboot2025:latest
          # SpÃ©cifie les architectures cibles
          #platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            USERNAME=${{secrets.DB_USER}}
            PASSWORD=${{secrets.DB_PASSWORD}}

      # message de fin indiquant que tout s'est bien passe
      - run: echo "ðŸ This job's status is ${{ job.status }}. ðŸ ðŸ†"

    Team_Notification:
      name: MS Teams Deploy Card
      runs-on: ubuntu-latest
      needs: docker-build-image-api
      steps:
        # this is the new step
        - uses: dchourasia/ms-teams-notification@1.0
          if: always()
          with:
            github-token: ${{ github.token }}
            webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}